name: pr-verify

on:
  pull_request:
    branches:
      - development
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          npm i
      - name: Verify ESLint
        run: |
          npm run lint
      - name: Run Unit Tests and Coverage
        run: |
          npm run test
      - name: Run E2E tests
        run: |
          npm run docker:start && npm run cypress:run && npm run docker:stop