name: pr-verify

on:
  pull_request:
    branches:
      - development
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          npm i
      - name: PR Verify
        run: |
          npm run verify