name: Pull Request

on:
  pull_request:
    branches:
      - development
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm i
      - name: Verify ESLint
        run: |
          npm run lint
      - name: Run Unit Tests and Coverage
        run: |
          npm run test
      - name: Create Docker Image
        run: |
          docker build -t "personal-website" ./
      - name: Run E2E tests
        run: |
          npm run docker:start && npm run cypress:run && npm run docker:stop