name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn install
      - name: Verify ESLint
        run: |
          yarn lint
      - name: Run Unit Tests and Coverage
        run: |
          yarn test
#      - name: Verify E2E tests
#        run: |
#          yarn start && yarn cypress:run